version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calcom
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  calcom:
    image: calcom/cal.com:latest
    container_name: calcom
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/calcom
      NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000
      JWT_SECRET: your-secret-key
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: postgres
      GENERIC_TIMEZONE: Europe/Berlin
    ports:
      - '5678:5678'
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
